name: GPU Market Daily

on:
  schedule:
    - cron: "17 05 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Update datasets
        run: python -m marketwatch.cli
      - name: Commit if changed
        shell: bash
        run: |
          git config user.name "market-bot"
          git config user.email "market-bot@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add -A
            git commit -m "chore(auto): gpu market daily refresh"
            git push https://x-access-token:${{ secrets.REPO_PAT }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
          else
            echo "No changes."
          fi
